import fs from 'node:fs';
fs.mkdirSync('relic_vale/scenes/dungeon_rooms',{recursive:true});
for(const kind of ['entrance','corridor','corner','crossroads','combat','large_combat','treasure','shrine','trap','elite','boss'])fs.writeFileSync('relic_vale/scenes/dungeon_rooms/'+kind+'.tscn',`[gd_scene load_steps=2 format=3]\n\n[ext_resource type="Script" path="res://scripts/world_generation/dungeon_room.gd" id="1"]\n\n[node name="${kind}" type="Node3D"]\nscript = ExtResource("1")\nroom_kind = "${kind}"\n`);
function edit(path,fn){let s=fs.readFileSync(path,'utf8').replaceAll('\r\n','\n');fs.writeFileSync(path,fn(s));}
edit('relic_vale/scripts/world_generation/settlement.gd',s=>s.replace('("windmill" if kind=="mining" else "market_stall")+".glb"','("mine" if kind=="mining" else "market")+".gltf.glb"').replace('"house.glb"','"house.gltf.glb"'));
edit('relic_vale/scripts/world_generation/story_poi.gd',s=>s.replace('world.place(world.VILLAGE+"cart.glb",Vector3(0,0,0),1.8,20,self)','world.box(Vector3(0,.65,0),Vector3(2,.2,1.1),"876046",false,self)\n\t\t\tfor x in [-.7,.7]:\n\t\t\t\tfor z in [-.65,.65]:\n\t\t\t\t\tvar wheel:=world.cylinder(Vector3(x,.45,z),.45,.16,"604334",12,self)\n\t\t\t\t\twheel.rotation_degrees.x=90\n\t\t\tworld.box(Vector3(1.5,.65,0),Vector3(1.6,.12,.12),"876046",false,self)'));
edit('relic_vale/scripts/combat/status_effects.gd',s=>s.replace('"might","shield"]','"might","shield","haste"]').replace('else 1.0\n','else (1.0+float(effects.haste.power) if has("haste") else 1.0)\n'));
edit('relic_vale/scripts/combat/boss.gd',s=>s.replace('var in_arena: bool=player.global_position.x>992 and player.global_position.x<1008 and player.global_position.z< -32 and player.global_position.z> -49','var arena: Rect2=actor.get_meta("arena",Rect2(992,-49,16,17))\n\tvar in_arena: bool=arena.has_point(Vector2(player.global_position.x,player.global_position.z))').replace('world.box(Vector3(1000,1,-31),Vector3(4.5,2,.35),"647f86",true,gate)','world.box(actor.get_meta("gate_position",Vector3(1000,1,-31)),actor.get_meta("gate_size",Vector3(4.5,2,.35)),"647f86",true,gate)').replace('minion.position=Vector3(1000+offset,0,-44)','minion.position=actor.origin+Vector3(offset,0,-4)'));
edit('relic_vale/scripts/combat/feedback.gd',s=>s.replace('shutting_down=true\n','shutting_down=true\n\tvar game=get_tree().current_scene\n\tif is_instance_valid(game) and is_instance_valid(game.get("life")): game.life.stop_audio()\n'));
edit('relic_vale/scripts/world_generation/living_world.gd',s=>s.replace('game=get_tree().current_scene\n','game=get_tree().current_scene\n\tValeSettlement.station(game.world,"forge",Vector3(8.8,0,-2),game.world)\n\tValeSettlement.station(game.world,"alchemy",Vector3(-3.8,0,-7.7),game.world)\n\tValeSettlement.station(game.world,"workbench",Vector3(12.5,0,4),game.world)\n\tValeSettlement.station(game.world,"campfire",Vector3(-4,0,7),game.world)\n'));
console.log('Room templates and integration adjustments prepared');
