import fs from 'node:fs';
const dir='relic_vale/data/narrative';fs.mkdirSync(dir,{recursive:true});
const write=(n,v)=>fs.writeFileSync(dir+'/'+n+'.json',JSON.stringify(v,null,2));
const companions={bren:{id:'bren',name:'Bren Alder',model:'res://assets/3d/phase4/adventurers/Knight.glb',portrait:'res://assets/ui/phase9/portraits/bren.png',biography:'A Lantern Compact shieldbearer who brought everyone home from Cinder Watch except the captain who ordered them to stay.',tags:['merciful','honorable','practical'],faction:'hearth',role:'melee',equipment:{Weapon:'iron_sword',Armor:'leather_vest',Accessory:''},abilities:[{id:'shield_rush',name:'Shield Rush',description:'Closes on a threat and briefly stuns it.',cooldown:9},{id:'hold_line',name:'Hold the Line',description:'Protects an injured traveler and draws nearby threats.',cooldown:16}],location:'bren_watch',camp_anchor:[-8,0,5],recruitment:'bren_recruit',personal:['bren_letters','bren_watchfire','bren_oath'],signature:'bren_watch_token',passive:'Stand Together',barks:{forest:'There is room on the path for both of us.',rain:'Keep your shield over the tinder. The rest can dry.',night:'I will take the first watch.',ruin:'Look for a way out before a way in.',boss:'I have your flank.',camp:'A roof is a promise someone intends to keep.'}}};
write('companions',companions);
const quests={};
function quest(id,name,description,stages,options={}){quests[id]={id,name,description,type:'narrative',target:id,count:stages.length,chain:'companion',category:'Companion',npc:'bren',stages,reward:{coins:15,shards:0,xp:30},...options};}
quest('bren_recruit','The Missing Dispatch','Bren will not leave the east road until he knows what happened to the runner carrying his dispatch.',[{type:'interact',target:'dispatch',text:'Search the fallen dispatch satchel.',location:'dispatch'},{type:'choice',target:'bren_recruit_choice',text:'Bring the dispatch back to Bren.',location:'bren_watch'}],{effects:[{type:'recruit',id:'bren'},{type:'approval',id:'bren',amount:12,key:'bren_recruited'}]});
quest('bren_letters','Letters Never Sent','At camp, Bren admits that his captain left a packet of letters at the abandoned watch.',[{type:'talk',target:'bren_letters_camp',text:'Hear Bren out at camp.',camp:true},{type:'interact',target:'watch_letters',text:'Recover the letters from Cinder Watch.',location:'cinder_watch'},{type:'talk',target:'bren_letters_return',text:'Read the last letter with Bren.',camp:true}],{conditions:[{type:'recruited',id:'bren'}],effects:[{type:'approval',id:'bren',amount:15,key:'bren_letters_done'},{type:'lore',id:'cinder_watch'}]});
quest('bren_watchfire','A Light for the Living','Bren wants to make Cinder Watch safe for the families who still use its road.',[{type:'defeat',target:'cinder_guard',text:'Defeat the oathbound sentry at Cinder Watch.',location:'cinder_watch'},{type:'interact',target:'watch_brazier',text:'Light the watch brazier.',location:'cinder_watch'},{type:'talk',target:'bren_fire_return',text:'Speak with Bren about the watch.',camp:true}],{prerequisites:['bren_letters'],conditions:[{type:'approval',id:'bren',value:20}],effects:[{type:'approval',id:'bren',amount:12,key:'bren_fire_done'},{type:'flag',id:'cinder_safe',value:true}]});
quest('bren_oath','Who Keeps the Watch','The Compact wants its outpost back. Bren would rather see a shelter where the old barracks stood.',[{type:'choice',target:'bren_oath_choice',text:'Decide the future of Cinder Watch with Bren.',camp:true}],{prerequisites:['bren_watchfire'],conditions:[{type:'approval',id:'bren',value:30}],effects:[{type:'item',id:'bren_watch_token',amount:1},{type:'approval',id:'bren',amount:15,key:'bren_oath_done'},{type:'flag',id:'bren_personal_complete',value:true}]});
write('quests',quests);
write('locations',{
 bren_watch:{name:'East Road Watch',address:{x:'0',z:'0',local:[17,0,8]},fixed:true,companion:'bren'},
 dispatch:{name:'Fallen dispatch',address:{x:'1',z:'0',local:[13,0,12]},objects:[{id:'dispatch',name:'Mud-stained dispatch satchel',model:'res://assets/3d/phase7/box.glb',height:.45,text:'The runner signed the last page: “Reached the ford. All six children accounted for.”'}]},
 cinder_watch:{name:'Cinder Watch',address:{x:'4',z:'3',local:[16,0,16]},objects:[{id:'watch_letters',name:'Unsent letters',model:'res://assets/3d/phase6/props/Book_Stack_1.gltf',height:.35,text:'The captain wrote to every family. He never asked the quartermaster to send the letters.'},{id:'watch_brazier',name:'Cold watch brazier',model:'res://assets/3d/phase7/campfire-pit.glb',height:.6,requires:[{type:'defeated',id:'cinder_guard'}],text:'The new fire burns low and steady. It is a signal to travelers, not an order to hold the wall.'}],enemies:[{id:'cinder_guard',archetype:'skeleton',offset:[4,0,-4]}],variant:'cinder_outcome'}
});
const dialogue={};
const choice=(id,text,effects=[],conditions=[],next='')=>({id,text,effects,conditions,next});
dialogue.bren_intro={speaker:'bren',text:'Six children crossed the ford with our runner. I found his boot. No runner. There should be a dispatch satchel by the east road. Bring it back, and I can stop imagining the worst.',choices:[choice('help','I will look for the satchel.',[{type:'start',id:'bren_recruit'}]),choice('later','Keep the fire going. I will return.')]};
dialogue.bren_recruit_choice={speaker:'bren',text:'“All six accounted for.” He made it. You have no idea what those four words are worth. Where are you headed?',choices:[choice('welcome','There is room beside my fire.',[{type:'event',event:'choice',id:'bren_recruit_choice'}]),choice('work','I could use someone who knows how to keep people alive.',[{type:'event',event:'choice',id:'bren_recruit_choice'}]),choice('later','Let me make arrangements first.')]};
dialogue.bren_camp={speaker:'bren',text:'I used to count bedrolls at night. I still do. Some habits are worth keeping.',choices:[choice('letters','What happened at Cinder Watch?',[{type:'start',id:'bren_letters'},{type:'event',event:'talk',id:'bren_letters_camp'}],[{type:'not_completed',id:'bren_letters'}],'bren_letters'),choice('return_letters','I brought the letters.',[{type:'event',event:'talk',id:'bren_letters_return'}],[{type:'stage',id:'bren_letters',value:2}],'bren_letters_end'),choice('watchfire','We could make the old watch safe again.',[{type:'start',id:'bren_watchfire'}],[{type:'completed',id:'bren_letters'},{type:'not_started',id:'bren_watchfire'},{type:'approval',id:'bren',value:20}]),choice('return_fire','The brazier is burning.',[{type:'event',event:'talk',id:'bren_fire_return'}],[{type:'stage',id:'bren_watchfire',value:2}],'bren_fire_end'),choice('oath','Who should keep the watch now?', [{type:'start',id:'bren_oath'}],[{type:'completed',id:'bren_watchfire'},{type:'not_completed',id:'bren_oath'},{type:'approval',id:'bren',value:30}],'bren_oath_choice'),choice('goodbye','Rest while the fire is warm.')]};
dialogue.bren_letters={speaker:'bren',text:'The captain ordered us to hold. The road behind us was full of families. I took my people out anyway. He stayed. His letters might explain why.',choices:[choice('listen','We can read them together.')]};
dialogue.bren_letters_end={speaker:'bren',text:'He knew the wall would fall. He stayed to give us time. I spent a year arguing with a dead man who had already forgiven me.',choices:[choice('kind','You brought people home. That matters.',[{type:'approval',id:'bren',amount:8,key:'bren_kind_words'}]),choice('honest','You may never have agreed. You can still remember him.',[{type:'approval',id:'bren',amount:5,key:'bren_honest_words'}])]};
dialogue.bren_fire_end={speaker:'bren',text:'A light on that road again. The Compact has asked for the keys. The families have asked for a roof. I want to hear what you think before I answer.',choices:[choice('consider','We should decide together.')]};
dialogue.bren_oath_choice={speaker:'bren',text:'A garrison could keep the road clear. A shelter would give travelers somewhere to stop. We have enough timber for one. Which promise do we make?',choices:[choice('shelter','Build a shelter. No traveler sleeps outside.',[{type:'flag',id:'cinder_outcome',value:'shelter'},{type:'reputation',id:'bough',amount:12},{type:'reputation',id:'hearth',amount:-6},{type:'approval',id:'bren',amount:8,key:'cinder_shelter'},{type:'event',event:'choice',id:'bren_oath_choice'}]),choice('garrison','Restore the garrison, with an open gate for travelers.',[{type:'flag',id:'cinder_outcome',value:'garrison'},{type:'reputation',id:'hearth',amount:15},{type:'reputation',id:'bough',amount:-5},{type:'approval',id:'bren',amount:3,key:'cinder_garrison'},{type:'event',event:'choice',id:'bren_oath_choice'}]),choice('later','We need more time.')]};
write('dialogue',dialogue);
write('lore',{cinder_watch:{id:'cinder_watch',category:'Places',title:'Cinder Watch',text:'The watch burned during the last evacuation of the east road. Its captain stayed behind while Bren Alder led the families through the ford. The surviving letters contain names, not orders.'}});
write('items',{bren_watch_token:{id:'bren_watch_token',name:'Watchkeeper’s token',kind:'equipment',rarity:'Rare',slot:'Accessory',stats:{max_hp:12,defense:2},base_price:45,icon:'shield',description:'Bren’s old watch token. A promise to count the living.'}});
console.log('Phase 9 vertical slice content: Bren, recruitment and three personal quests.');
